# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals Docker Agent - Windows

variables:
  buildDir: '$(System.DefaultWorkingDirectory)/target'

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build
    displayName: "Build Job"
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        goals: 'clean package'

    - script: |
        echo "Contents of $(buildDir):"
        dir $(buildDir)
      displayName: "List Build Directory"

- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: Test
    displayName: "Test Job"
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'test'

- stage: Deliver
  displayName: "Deliver Stage"
  dependsOn: Test
  jobs:
  - job: Deliver
    displayName: "Deliver Job"
    steps:
    - script: |
        echo "Debug: Checking $(buildDir)"
        if not exist "$(buildDir)\*.war" (
          echo "No WAR files found in $(buildDir)"
        ) else (
          echo "Copying WAR files to deliverables"
          if not exist "$(buildDir)\deliverables" mkdir "$(buildDir)\deliverables"
          for %%f in ("$(buildDir)\*.war") do copy "%%f" "$(buildDir)\deliverables\
